export function exportXAirSnapshot(graph) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const lines = [
    `# XAir18 state dump - generated by MixFlow - ${timestamp}`,
    `# target: Behringer X Air 18 (XR18 / X18 / MR18)`
  ];

  const inputs = Array.from(graph.nodes.values()).filter(n => n.category === 'input');
  const strips = Array.from(graph.nodes.values()).filter(n => n.category === 'strip');
  const usbSends = Array.from(graph.nodes.values()).filter(n => n.category === 'usb_send');

  // Input Channels 1-16
  for (let i = 1; i <= 16; i++) {
    const chStr = i.toString().padStart(2, '0');
    const inputNode = inputs.find(n => n.getProperty('channelIndex') === i);
    const stripNode = strips.find(n => n.getProperty('channelIndex') === i);
    const usbNode = usbSends.find(n => n.getProperty('channelIndex') === i);

    const name = stripNode?.getProperty('name') || inputNode?.getProperty('name') || '';
    const rtnsw = stripNode?.getProperty('rtnsw') ? 1 : 0;
    const fader = stripNode?.getProperty('fader') !== undefined ? stripNode.getProperty('fader').toFixed(1) : '0.0';
    const on = stripNode?.getProperty('muted') ? 'OFF' : 'ON';
    const gainVal = inputNode?.getProperty('gain') !== undefined ? (inputNode.getProperty('gain') >= 0 ? `+${inputNode.getProperty('gain').toFixed(1)}` : inputNode.getProperty('gain').toFixed(1)) : '0.0';
    const phantom = inputNode?.getProperty('phantom') ? 'ON' : 'OFF';

    lines.push(`/ch/${chStr}/config "${name}" 0 In${chStr} U${chStr}`);
    lines.push(`/ch/${chStr}/preamp 0.0 OFF OFF OFF 20.0 ${rtnsw}`);
    lines.push(`/ch/${chStr}/gate OFF GATE -80.0 60.0 1 502 983 SELF`);
    lines.push(`/ch/${chStr}/dyn OFF COMP PEAK LOG 0.0 3.0 1 0.00 10 10.0 151 100 SELF OFF`);
    lines.push(`/ch/${chStr}/eq ON`);
    lines.push(`/ch/${chStr}/mix ${on} ${fader} ON 0.0000`);
    
    // Headamp 01-16
    lines.push(`/headamp/${chStr} ${gainVal} ${phantom}`);
  }

  // Aux return
  lines.push(`/rtn/aux/config "Aux/USB" 0`);
  lines.push(`/rtn/aux/mix ON 0.0 ON 0.0000`);

  // Main LR
  const mainNode = Array.from(graph.nodes.values()).find(n => n.category === 'main');
  const mainFader = mainNode?.getProperty('masterFader') !== undefined ? mainNode.getProperty('masterFader').toFixed(1) : '0.0';
  lines.push(`/lr/config "Main PA" 6`);
  lines.push(`/lr/mix ON ${mainFader} 0.0000`);

  return lines.join('\n') + '\n';
}
